### ISSUE TITLE
Controlling Hyperdeck functions & clips

### ISSUE THREAD

**Issue by randallpacker** [danielbuechele/atemOSC#102]
I just saw the thread earlier this year about controlling Hyperdecks from ATEMOSC. Has there been any progress on this? I am more than willing to test. 

Thank you!

Randall Packer

**Comment by SteffeyDev** [comment]
See #58, thanks for the additional input.

**Comment by randallpacker** [comment]
I read this already and was wondering if there has been any progress since the last message in march. Sounds like there was no final decision made.

**Comment by SteffeyDev** [comment]
I think we can add it, for me I would just need to find time. Not having a hyperdeck is another barrier, because I don’t even know how the initial connection works nor do I know how the device itself is supposed to function. If someone in the community that has a Hyperdeck and knows Objective-C has time, that would be ideal.

**Comment by randallpacker** [comment]
Figured out a very simple solution to controlling the hyperdeck: just create macros that control each function and specific clips. One macro per function or clip, then trigger the macros in atemosc. Maybe someone thought of this already because it is so wonderfully simple.
