### ISSUE TITLE
Maintenance of this project

### ISSUE THREAD

**Issue by danielbuechele** [danielbuechele/atemOSC#36]
I am not anymore in the possession of an ATEM device. This makes it really hard for me to maintain this project. On the other hand I don't want this project to die and I myself use this software still from time to time.

Perhaps @sneat, @SteffeyDev or anybody else is interested in overtaking this project. I would offer some help in building a TravisCI build-job, perhaps a little website, better readme and so on.

**Comment by sneat** [comment]
Happy to help as I too still sometimes find it handy.

**Comment by danielbuechele** [comment]
Happy to hear that! What do you think would be a good way of maintaining the repo? Should I just add you as an admin for this repo? Or do you want to maintain it under your name? Or should we create a organization?

**Comment by SteffeyDev** [comment]
I don't think I could take over the project but I would be happy to help maintain it, I have access to an ATEM Production Studio 4K on the weekends for testing.

**Comment by sneat** [comment]
I'm happy either way and I don't think it matter too much either way.

Keeping the same location:
Pros: URLs don't change (e.g. google)
Cons: You need to give access to a repo under your account

Changing to an org:
Pros: It's clearer that it's a joint effort
Cons: URLs need to change

**Comment by danielbuechele** [comment]
I added both of you as collaborators to this repo. I think for now this is the easiest way. We can still later decide to move it to an org. Please, feel free to change whatever you like.
Right now, the compiled app is part of the repo, which isn't really a good idea. I think we should move it to the GitHub releases feature

**Comment by SteffeyDev** [comment]
Thanks for adding us.  I agree in moving to Github releases, I also think a cool long-term project would be an actual website (or github page) with the downloadable app for each Blackmagic SDK version, so that it would be easy for people who aren’t familiar or comfortable with git to download AtemOSC.

**Comment by SteffeyDev** [comment]
@danielbuechele Three questions:

1) How do you feel about API changes? Obviously while maintaining backword comparability.  I would love to move USK api to more of the style like DSK, so /atem/usk/tie/1 instead of /atem/nextusk/1, or something along those lines.  I’d also like to expand the ftb commands to have a set command and a transition level command. If you are up for api changes I can open a an issue to discuss the specific changes I have in mind.

2) Is it ok if we follow up on and close issues, or do you want to remain responsible for that sort of maintenance on the repository? 

3) How do you feel about a full program refactor?  The app delegate class seems really bloated and still has unnecessary remnants of the sample app you based the original code base off of.  I think by splitting some of the code out into separate files, using callbacks instead of passing self object references, and getting rid of leftover code from the sample app that is not used could make future development on this project much easier.

**Comment by danielbuechele** [comment]
1. I think API changes are fine, usually OSC addresses are fairly easy to change. When maintaining backwards compatibility, just go ahead!
2. Please, go for it! They are open for quite a time, some of them might be outdated, or need to be consolidated. Feel free to organize them the way you think it makes the most sense.
3. Sure, feel free to do this. Also we could get rid of the Arduino tally code, as I am pretty sure I was the only ever user of it. When cleaning up the code, we might also think about a better way for generating the OSC addresses help panel.

So glad you are joining!

**Comment by iamjohnbarker** [comment]
I'm happy to help out if needed for building out a site, design tasks, wiki and informational video content. ([I made this one already](https://www.youtube.com/watch?v=HQm2KZYcPws)).

I'm not much of a dev, but keen to give back to the project as I use it all the time and promote it 😄

**Comment by danielbuechele** [comment]
@iamjohnbarker This is great and exactly what we need. I think a small website (one pager) explaining the features, showing screenshots, video tutorials, etc. would be really helpful. I'll create an issue for this and would love to hear your thoughts.
