### ISSUE TITLE
Change ATEM IP Address while connected

### ISSUE THREAD

**Issue by SteffeyDev** [danielbuechele/atemOSC#48]
Currently, once an ATEM is connected, changing the IP address has no effect.  Either the text field should be locked to prevent editing the IP address after connected, or if the IP address is changed atemOSC should disconnect from the current switcher and try to connect to the new IP.  Or else something to address the fact that the switcher IP address textfield is useless after the initial connection, as it feels odd to be editing a text field with no feedback or response from the application.  Maybe this can be addressed as part of #45.

**Comment by danielbuechele** [comment]
I think making the textfield read-only once the switcher is connected is a good choice, because you don't really want to accidentally disconnect. Also, I think the vast majority only has one device which the software should connect to.

**Comment by aaronpk** [comment]
This just tripped me up. Between the time I first used this and just now, I've changed the IP address of my ATEM. I thought I would be able to change the IP address in the interface, so I was confused why it wasn't connecting. I quit and re-launched the app and everything was fine of course. I'm not sure how you'd be able to change the IP address if the text field was disabled since there is no connect/disconnect button.

**Comment by SteffeyDev** [comment]
@aaronpk That's a great points, we may need a "Change IP" or "Disconnect" button post-connection to allow for changing hosts mid-session.

Alternatively, as a part of a UI overhaul we could start supporting multiple hosts and "stored hosts" out of the box, similar to how VPN and RDP apps store previous connections in a list for quick connections.  That would be a big change though.
