### ISSUE TITLE
API Consistency Update

### ISSUE THREAD

**Issue by avmaint** [danielbuechele/atemOSC#66]
I think there could be some more clarity on the documentation for /atem/aux. 
The way I read the doc, i thought "/atem/aux/1 2" would change aux 1 to source 2. But I now think it should be "/atem/aux/1" with a float value of 2 in the message.

**Comment by SteffeyDev** [comment]
What's the difference between your first thought and second?  In the world of OSC, "/atem/aux/1 2" means "Send OSC message with address of /atem/aux/1 and integer value of 2".  If you want, we could include a quick blurb about how OSC addressing schemes work at the top of the README.  Would that resolve your issue or what kind of documentation change do you have in mind?

**Comment by avmaint** [comment]
The difference is ambiguous meaning in the notation. The possibilities I came up with:
1) The address is "/atem/aux/1 2"
2) The address is "/atem/aux/1" and The space is meant to indicate a break between address and payload. The payload value is a int with value "2".

In some of the other command doc, it say 'send a value' - which to me is more clear that it is not part of the address. For example "/atem/set-nextusk/$i <0|1>" uses that style.

In other commands, the $x does appear to be part of the address. For example: "/atem/mplayer/$i/still/$x"

**Comment by kutuz00** [comment]
Is there possible to run command or add for push PGM (program) output to aux?

**Comment by sneat** [comment]
@kutuz00 yes, you can do that already. If you open up the Help→OSC Addresses menu and find the value for "Program" under the Sources section (it will look something like this `Program: /atem/program/10010`) and then use that in combination with the "Aux Outputs" section

```
Aux Outputs:
	Set Aux X to Source: /atem/aux/X	<valid_program_source>
```

So for instance, if you wanted to set Aux 1 output to be sending the Program feed, you would send the command:

```
Address: /atem/aux/1
Value: 10010
```

**Comment by jeffmann** [comment]
[**@avmaint**](https://github.com/avmaint) commented on [Feb 20, 2018, 12:21 PM GMT+1](https://github.com/danielbuechele/atemOSC/issues/66#issuecomment-366947107 "2018-02-20T11:21:11Z - Replied by Github Reply Comments"):
> The difference is ambiguous meaning in the notation. The possibilities I came up with:
> 
> 1.  The address is "/atem/aux/1 2"
> 2.  The address is "/atem/aux/1" and The space is meant to indicate a break between address and payload. The payload value is a int with value "2".
> 
> In some of the other command doc, it say 'send a value' - which to me is more clear that it is not part of the address. For example "/atem/set-nextusk/$i &lt;0|1&gt;" uses that style.

Since OSC addresses can't contain spaces (just like URLs) then *2.* is unambiguously the meaning. I don't think there's a problem with that notation, as *1.* is impossible.

> 
> In other commands, the $x does appear to be part of the address. For example: "/atem/mplayer/$i/still/$x"

I agree that's confusing. The addressing is not consistent, sometimes the input is selected with an argument:
/atem/aux/1 5
/atem/aux/2 3
and sometimes as part of the address:
/atem/program/5
/atem/preview/3

Personally I think the first form is better, and I would expect to select the program/preview source with an argument:
/atem/program 5

Similarly with other things, eg.:
/atem/transition/set-type [mix|dip|wipe|sting|dve] (string)
/atem/set-nextusk [1-4] [0|1]
/atem/transition [cut|auto|ftb|bar [0.-1.]]
/atem/usk [1-4]
etc.

But probably there's a good reason for it being the way it is - ease of programming - and probably too late to change now. I don't find it a big problem, and I'm certainly not going to ask for my money back because of it :-)

**Comment by SteffeyDev** [comment]
I've been intending to update the API at some point (with backwards compatibility), but it's not currently a priority.

**Comment by SteffeyDev** [comment]
I'm going to change this issue into the API Update issue, because that seems to be the main pain point discussed here.

**Comment by SteffeyDev** [comment]
It is worth noting that I think the original API was designed the way it was because TouchOSC only supports sending floats as values, and cannot send strings.  Obviously this is only one use case, but any changes moving forward will have to keep this in mind and maintain the old API documented as a method for TouchOSC and other apps to send OSC signals that don't support sending strings.

**Comment by carbon43** [comment]
I really wish Rob would stop d***ing around with Kodelife and get back to working on TouchOSC. Its such a great app with lots of potential, but it makes me nervous that its gone so long without any updates....

**Comment by SteffeyDev** [comment]
Ok, let's talk about API

I'm redo-ing the USK API right now while I'm adding the new feature (#85), and while I'm at it also redo-ing the DSK API to match.  Here is what I have so far:

### USK
`/atem/usk/set-on-air/#`
`/atem/usk/toggle-on-air/#`
`/atem/usk/set-tie/#`
`/atem/usk/toggle-tie/#`
`/atem/usk/set-next/#`

### DSK
`/atem/dsk/set-on-air/#`
`/atem/dsk/auto-on-air/#`
`/atem/dsk/toggle-on-air/#`
`/atem/dsk/set-tie/#`
`/atem/dsk/toggle-tie/#`
`/atem/dsk/set-next/#`

Note that they are very similar, and should make the learning curve a bit easier.

Here's what I need feedback on:
* Should `set-tie` be just `tie`, and `set-on-air` be just `on-air`?  Or does having the `set` prefix make more sense (in the context of the other prefixes of `toggle` and `auto`)?
* Should the number come before the command? For example, should it be `/atem/dsk/set-tie/5 1` or `/arem/dsk/5/set-tie 1`?  They read slightly differently.

I'm hoping that if we can establish the precedence here regarding prefix and ordering, the rest of the API changes will make a lot more sense.  So let me know what you think!

**Comment by SteffeyDev** [comment]
@danielbuechele @sneat @carbon43 @jeffmann @kutuz00 I would appreciate some feedback on this if you have the chance, I'm ready to push the changes but still have the same questions.

**Comment by jeffmann** [comment]
The way I think of it, OSC addresses are *addresses*, not commands. It's the location of something, a control like a button on a control panel. You send some data to the control, to say what to set the control to.

For example, I would expect something like:

`/atem/dsk/2/on-air` corresponds to the on-air button for dsk 2. Sending:
`/atem/dsk/2/on-air 1|0` forces it on or off respectively.
`/atem/dsk/2/on-air` with no argument is a default "press" of the button, so in this case toggle.
`/atem/dsk/2/auto` - press the auto button of dsk 2.

(Actually, in my own projects I use the `Impulse` type as an argument for a default "press" or "click" of the control. An address with no argument is a query or "get" - but maybe that's too radical? Probably a lot of implementations don't support `Impulse`?)

The order is important if there could be support of the "*" wildcard, eg.:
`/atem/dsk/*/on-air 0` force all dsks off-air.

So for your example: `/atem/dsk/5/tie 1` forces the tie on for dsk 5. If I'm understanding the question right that is... is there an ATEM with 5 dsks?

**Comment by SteffeyDev** [comment]
Because users are coming from a background of physical or software buttons to control their switchers, I like the idea of that.  It would definitely simplify the API.  The only concern I would have is the ambiguity involved with the existence of an argument changing the functionality, but I don't think that is a huge issue.

I think the bigger issue is with compatibility, because I know that at least TouchOSC *always* sends a value, so this would force all TouchOSC users to go through a router of some kind.  There may be other applications that behave similarly.  However, we could consider (following your example) also supporting `/atem/dsk/2/on-air/toggle` as a compatibility patch of sorts, but state that `/atem/dsk/2/on-air` with no arguments is preferred.

Of course, the DSK 5 was simply hypothetical :)

I also like the idea of supporting wildcards, I may open another issue just for that.

And I haven't heard of the `Impluse` type, I'll have to do some research on that. Might be a bit much for the range of compatibility we are going for.

Thanks @jeffmann  for all the ideas!

**Comment by jeffmann** [comment]
The ambiguity is why I like `Impulse`:
>OSC 1.1 required types
The   1.1   specification   moves   some   types   previously 
specified  as  optional  into  the  required  list  resulting  in  the 
following  (Table 1):
[...]
I Impulse:  (aka  “bang”),  used  for  event  triggers.  No bytes  are  allocated  in  the  argument  data.  This  type was named “Infinitum” in OSC 1.0

Doesn't seem like TouchOSC supports it though, and it does look like it always has to send an argument for its buttons. So that makes it kind of difficult. Another way could be:
`/atem/dsk/2/on-air/state 0|1`
`/atem/dsk/2/on-air/toggle 1`
and also support:
`/atem/dsk/2/on-air 0|1|Impulse/no arg` ??

Not sure what I like better...

**Comment by SteffeyDev** [comment]
Update: Just saw your latest message, so here are some additional thoughts

If we were to implement a query in the future, it would probably be something like `/atem/dsk/2/on-air/status`.  That way, we can say that `/status` on the end of any command (that supports it) always returns the status.  However, I would have to look more about how querying is intended in the OSC standard before committing to that.

I see your point about TouchOSC users not really wanting a toggle.  It seems that the people who want the toggle are in the OSCulator camp, using MIDI buttons that don't inherently have a state.  That being said, I don't want to artificially limit the usability of the API because of some perception of what may or may not be used.

In addition, I stand by my defense of not allowing blank values to have a meaning in this context, because for clarity I want each address to either accept a value, or for that specific address to be value-less (will trigger regardless of value).  `/atem/transition/cut` is value-less, and will cut regardless of whether or not you send a value.  I think this makes it very easy for MIDI users, because they don't have to worry about clearing garbage values that may or may not be sent by their MIDI-to-OSC translator.

**Comment by jeffmann** [comment]
I agree, the Impulse type is relatively rare. I think osc4py3 and SuperCollider support it, not sure what else. Probably not worth the effort. Even Adrian Freed - one of the authors of the paper making it "required" - doesn't support it in CNMAT's odot or OSC for Arduino...

> It seems that the people who want the toggle are in the OSCulator camp, using MIDI buttons that don't inherently have a state.

But are they also unable to send with no argument? Isn't that something pretty specific to TouchOSC?

> The only reason I am not supporting blank argument as a toggle here is because I think it would add more confusion to new users

I'm not sure about that... I think the least confusing to people is going to be if the OSC addresses correspond to the actual buttons and controls on the ATEM software/hardware control panel (or maybe blocks of buttons as in the case of the Program/Preview bus). Sending `/atem/transition/cut` and `/atem/dsk/2/auto` means literally "press that button on the control panel". With `/atem/dsk/2/on-air`, it should be the same. I can understand that there are these optional arguments for the on-air button, 1 or 0, where I can explicitly set it on or off. What I find very confusing is mixing in addresses that don't correspond to a button on the control panel, like `/atem/dsk/2/on-air/toggle`. Where do I find that? "Toggle" should be an argument (or lack thereof), not part of an address, a non-existent button.

To me, `/atem/dsk/2/on-air` (a button) with `0 or 1 to set, no argument to toggle` is straightforward and easy to understand, whereas `/atem/dsk/2/on-air` (a button) with `0 or 1 to set`, plus `/atem/dsk/2/on-air/toggle` (not a button) with `argument doesn't matter` is much less so.

When I read the comment:
>[...]
/atem/dsk/set-on-air/#
/atem/dsk/auto-on-air/#
/atem/dsk/toggle-on-air/#
[...]

I was actually quite confused, that's why I didn't answer. I had to look at it for a long time, and look through the ATEM manual, to understand that some of them correspond to actual buttons, and some of them not.

Maybe the /toggle is necessary as a compatibility hack/workaround for a limitation in TouchOSC, or for people who have problems with clearing garbage values etc., I'm not sure... but I am pretty sure it takes away from the clarity rather than adding to it. If it really has to be implemented, probably do it in addition to no argument to toggle, and put it as a footnote to the documentation.

**Comment by SteffeyDev** [comment]
> But are they also unable to send with no argument? Isn't that something pretty specific to TouchOSC?

They certainly can send with no argument, it just takes a little more work on their part.

Here's a question that could clear things up a bit.  If you want OSC addresses to correspond to buttons, what would you do for the `set-next` method, which doesn't correspond to any physical button but is still very useful?  What about other methods in the future that are stateful and more powerful than just pressing buttons?

I love the idea of corresponding to buttons, but I also feel like it is restrictive of the power of OSC and what atemOSC can do.  If you can find a place in your imagined API for commands like `set-next`, I think I would be much more open to it.

Whereas you are looking at mapping addresses to buttons, I am looking at it from the OSC spec: there are "OSC Containers" and then there are "methods".   

> Every OSC server has a set of OSC Methods. OSC Methods are the potential destinations of OSC messages received by the OSC server and correspond to each of the points of control that the application makes available. "Invoking" an OSC method is analogous to a procedure call; it means supplying the method with arguments and causing the method's effect to take place.

`/atem/dsk/2/on-air` is a container that happens to correspond to a physical button, and within that container there are several methods, such as `toggle` and `set`.  We could also later add a `get`/`status` method.  I would actually consider putting `auto` under `on-air`, so that you have `/atem/dsk/2/on-air/auto`.  In that way, each DSK has two sub-containers: `tie` and `on-air`, and you can call methods within those containers.

> I was actually quite confused, that's why I didn't answer. I had to look at it for a long time, and look through the ATEM manual, to understand that some of them correspond to actual buttons, and some of them not.

That's true, so maybe I preface the API by saying that this is OSC, and thus the API need not correspond to physical buttons (although it bears a resemblance/similarity).

I really appreciate your feedback, as it has forced me to reconsider the options and re-think what the API can be.  I would also appreciate feedback from @danielbuechele or @sneat on this matter as well, as well as anyone else who uses the application, because I truly do want to make an informed decision.

**Comment by SteffeyDev** [comment]
@jeffmann Check out v2.5.4 and the new README with the new API, and let me know what you think.  I think what I ended up doing is pretty similar to what you wanted, except without the `Impulse` because of the lack of support from the underlying framework.
